require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 165
  Exclude:
    - 'bin/bundle'

# We use arrays to group multiple similar specs under a single implementation
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 26
  Exclude:
    - 'bin/bundle'
    - 'db/migrate/*'

Metrics/BlockLength:
  Max: 40
  CountAsOne: ['array', 'heredoc']
  Exclude:
    - 'app/api/goggles/*_api.rb'
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'app/api/goggles/calendars_api.rb'
    - 'app/api/goggles/meetings_api.rb'
    - 'app/api/goggles/meeting_reservations_api.rb'
    - 'app/api/goggles/user_results_api.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/MethodLength:
  Max: 35

Metrics/ModuleLength:
  Exclude:
    - 'app/api/goggles/api_helpers.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'


# We use arrays to group multiple similar specs under a single implementation
Performance/CollectionLiteralInLoop:
  Exclude:
    - 'spec/**/*'


# Configuration parameters: EnforcedStyle, AllowToTime.
# SupportedStyles: strict, flexible
Rails/Date:
  Exclude:
    - 'spec/support/shared_api_response_behaviors.rb'

RSpec/ExpectInHook:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

# Configuration parameters: Include, CustomTransform, IgnoreMethods, SpecSuffixOnly.
# Include: **/*_spec*rb*, **/spec/**/*
RSpec/FilePath:
  Exclude:
    - 'spec/performances/swimmers_api_spec.rb'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 18

RSpec/NestedGroups:
  Max: 5

Style/ClassAndModuleChildren:
  Exclude:
  - 'api/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/application.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
