FORMAT: 1A
HOST: https://master-goggles.org

# Goggles 'core7' API
Backend internal API for the Goggles Engine, core7.

    | _Framework_ | _API_ | _App version_ | _DB structure_ | _latest update_ |
    | --- | --- | --- | --- | --- |
    | `core7` | `v3` | 7.41 | 1.37.01 | 20201210 |

_Previous legacy versions are deprecated and subseeded by this._

<!-- include(blueprint/session.apib) -->

<!-- include(blueprint/badges.apib) -->
<!-- include(blueprint/swimmers.apib) -->
<!-- include(blueprint/swimming_pools.apib) -->
<!-- include(blueprint/seasons.apib) -->
<!-- include(blueprint/teams.apib) -->
<!-- include(blueprint/team_affiliations.apib) -->
<!-- include(blueprint/team_managers.apib) -->
<!-- include(blueprint/users.apib) -->
