version: '3.7'

services:
  goggles-db:
    image: mariadb:10.3.25
    container_name: goggles-db
    env_file:
      - .env
    ports:
      - '33060:3306'
    restart: always
    volumes:
      - "~/Projects/goggles_deploy/db.prod:/var/lib/mysql"

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: "steveoro/goggles-api:prod-${TAG}"
    depends_on:
      - goggles-db
    container_name: goggles-api
    env_file:
      - .env
    ports:
      - '8081:8081'
    restart: always
    volumes:
      - "~/Projects/goggles_deploy/db.prod:/var/lib/mysql"
      - "~/Projects/goggles_deploy/backups:/app/db/dump"
      - "~/Projects/goggles_deploy/log.prod/api:/app/log"
      - "~/Projects/goggles_deploy/master-api.key:/app/config/master.key"

networks:
  default:
    name: prod

volumes:
  gem_cache:
  node_modules:
