# Group Laps

## Lap details [/api/v3/lap/{id}]

+ Model (application/json)

        {
            "id": 9982,
            "lock_version": 0,
            "minutes": 0,
            "seconds": 13,
            "hundredths": 9,
            "meeting_program_id": 161992,
            "length_in_meters": 25,
            "created_at": "2019-08-08T15:41:34.000Z",
            "updated_at": "2019-08-08T15:41:34.000Z",
            "reaction_time": "0.0",
            "stroke_cycles": null,
            "underwater_seconds": null,
            "underwater_hundredths": null,
            "underwater_kicks": null,
            "breath_cycles": null,
            "position": null,
            "minutes_from_start": 0,
            "seconds_from_start": 13,
            "hundredths_from_start": 9,
            "meeting_individual_result_id": 835064,
            "meeting_entry_id": null,
            "swimmer_id": 1452,
            "team_id": 1,

            "meeting_program": {
                "id": 161992,
                "event_order": 106,
                "category_type_id": 1248,
                "gender_type_id": 1,
                "autofilled": true,
                "out_of_race": false,
                "begin_time": "2000-01-01T19:22:00.000Z",
                "meeting_event_id": 19628,
                "pool_type_id": 1,
                "time_standard_id": null,

                "pool_type": {
                    "id": 1,
                    "code": "25",
                    "length_in_meters": 25,
                    "eventable": true,
                    "label": "25 M",
                    "long_label": "25 METERS",
                    "alt_label": "25 M"
                },

                "event_type": {
                    "id": 2,
                    "code": "50SL",
                    "length_in_meters": 50,
                    "relay": false,
                    "stroke_type_id": 1,
                    "style_order": 2,
                    "mixed_gender": false,
                    "partecipants": 1,
                    "phases": 1,
                    "phase_length_in_meters": 50,
                    "label": "50 FS",
                    "long_label": "50 FREESTYLE",
                    "alt_label": "50 FS"
                },

                "category_type": {
                    "id": 1248,
                    "code": "M30",
                    "federation_code": "C",
                    "description": "MASTER 30",
                    "short_name": "M30",
                    "group_name": "MASTER",
                    "age_begin": 30,
                    "age_end": 34,
                    "relay": false,
                    "season_id": 182,
                    "out_of_race": false,
                    "undivided": false
                },

                "gender_type": {
                    "id": 1,
                    "code": "M",
                    "label": "MAL",
                    "long_label": "MALE",
                    "alt_label": "MALE"
                },

                "stroke_type": {
                    "id": 1,
                    "code": "SL",
                    "eventable": true,
                    "label": "FS",
                    "long_label": "FREESTYLE",
                    "alt_label": "CR"
                }
            },

            "swimmer": {
                "id": 1452,
                "complete_name": "Grimes Darcie 35660",
                "last_name": "Grimes",
                "first_name": "Darcie",
                "year_of_birth": 1934,
                "year_guessed": false
            },

            "team": {
                "id": 1,
                "name": "Lake Ramiro Swimming Club ASD",
                "editable_name": "Lake Ramiro Swimming Club ASD",
                "address": "9038 Littel Lights",
                "zip": "028088",
                "phone_mobile": "265-752-0508 x022",
                "phone_number": "493-278-0409",
                "fax_number": null,
                "e_mail": "zenaida@example.net",
                "contact_name": "Dede Sipes",
                "notes": "Meatloaf rump pork ribeye shank sirloin venison tongue.",
                "name_variations": null,
                "city_id": 37,
                "home_page_url": "http://watsica.us",
                "city": {
                    "id": 37,
                    "name": "Reggio nell Emilia",
                    "zip": "?",
                    "area": "Reggio Emilia",
                    "country": "Italy",
                    "country_code": "IT",
                    "latitude": "44.716667",
                    "longitude": "10.6",
                    "region": "Emilia-Romagna",
                    "area_code": "RE"
                }
            },

            "meeting": {
                "id": 18270,
                "code": "bolognanuovonuoto",
                "header_year": "2018/2019",
                "edition_label": "XIX"
            },

            "meeting_individual_result": {
                "id": 835064,
                "rank": 4,
                "play_off": true,
                "out_of_race": false,
                "disqualified": false,
                "standard_points": "818.45",
                "meeting_points": "818.45",
                "minutes": 0,
                "seconds": 27,
                "hundredths": 21,
                "meeting_program_id": 161992,
                "swimmer_id": 1452,
                "team_id": 1,
                "badge_id": 111399,
                "disqualification_code_type_id": null,
                "goggle_cup_points": "995.96",
                "reaction_time": "0.0",
                "team_points": "0.0",
                "team_affiliation_id": 5197,
                "personal_best": false,
                "season_type_best": false,

                "team_affiliation": {
                    "id": 5197,
                    "number": "46103",
                    "name": "CSI NUOTO OBER FERRARI",
                    "compute_gogglecup": true,
                    "team_id": 1,
                    "season_id": 182,
                    "autofilled": false
                },

                "swimmer": {
                    "id": 1452,
                    "complete_name": "Grimes Darcie 35660",
                    "last_name": "Grimes",
                    "first_name": "Darcie",
                    "year_of_birth": 1934,
                    "year_guessed": false
                },
                "disqualification_code_type": null
            },

            "event_type": {
                "id": 2,
                "code": "50SL",
                "length_in_meters": 50,
                "relay": false,
                "stroke_type_id": 1,
                "style_order": 2,
                "mixed_gender": false,
                "partecipants": 1,
                "phases": 1,
                "phase_length_in_meters": 50,
                "label": "50 FS",
                "long_label": "50 FREESTYLE",
                "alt_label": "50 FS"
            },

            "pool_type": {
                "id": 1,
                "code": "25",
                "length_in_meters": 25,
                "eventable": true,
                "label": "25 M",
                "long_label": "25 METERS",
                "alt_label": "25 M"
            }
        }


### find [GET]
The Lap instance matching the specified `id` returned as JSON.

The returned detailed result includes some of its parents and more: take a look at the structure aside for more details.

Some of the sub-entities (such as the GenderType) are duplicated in the hierachy tree for ease of reference.

:key: `Authorization` request header => valid JWT **required**


* * *


+ Parameters
    + id: 9976 (number, required) - Lap ID


+ Request ok (application/json)

    #### Examples

    ##### `curl` (Bash):

    ```bash
    $> curl -i -X GET -H "Content-Type: application/json" \
            -H 'Authorization: "Bearer VALID-SESSION-JWT"' \
            "<API_HOST:PORT>/api/v3/lap/9976"
    ```

    ##### `RestClient` (Ruby):

    ```ruby
    > res = RestClient::Request.execute(
                method: :get,
                url: '<API_HOST:PORT>/api/v3/lap/9976',
                headers: { "Authorization" => "Bearer VALID-SESSION-JWT" }
            )
    => <RestClient::Response 200 "{\"id\":9976, ...">
    ```


    * * *

    + Header

            Authorization: "Bearer VALID-SESSION-JWT"

+ Response 200

    [Lap details][]


+ Request not found (application/json)

    + Header

            Authorization: "Bearer VALID-SESSION-JWT"

+ Response 200 (application/json)

        null


+ Request bad JWT (application/json)

    All JWTs expire: see [Session API docs](#sessions-session-post) for info.

    + Header

            Authorization: "Bearer BAD-OR-EXPIRED-JWT"

+ Response 401 (application/json)

    + Header

            X-Error-Detail: "Invalid JWT token"

    + Body

            { "msg": "Unauthorized" }

+ Request no JWT (application/json)

+ Response 401 (application/json)


    + Header

            X-Error-Detail: "Missing JWT token"

    + Body

            { "msg": "Unauthorized" }



## edit [PUT]

Allows direct updates for all the Lap fields given the `id` of the row.

Returns `true` on success, an empty result when not found.

:key: => satisfy both conditions:
1. `Authorization` request header => valid JWT **required**
2. authenticated user must have CRUD grant on 'Lap' or have generic admin grants


#### Body Attributes:

All are optional (except `id`):

|  Field name  | Data type |  description |
| --- | --- | --- |
| `meeting_individual_result_id` | integer | associated MeetingIndividualResult ID |
| `meeting_program_id` | integer | associated MeetingProgram ID |
| `team_id` | integer | associated Team ID |
| `swimmer_id` | integer | associated Swimmer ID |
| `reaction_time` | float | reaction time (when available; must be positive to be considered) |
| `minutes` | integer | lap time, minutes |
| `seconds` | integer | lap time, seconds |
| `hundredths` | integer | lap time, hundredths of seconds |
| `length_in_meters` | integer | lap length in meters |
| `minutes_from_start` | integer | overall minutes from heat start |
| `seconds_from_start` | integer | overall seconds from heat start |
| `hundredths_from_start` | integer | overall hundredths of second from heat start |
| `stroke_cycles` | integer | lap overall stroke cycles |
| `underwater_seconds` | integer | time spent underwater on turn/start, seconds |
| `underwater_hundredths` | integer | time spent underwater on turn/start, hundredths of a second |
| `underwater_kicks` | integer | underwater kicks after lap turn/start |
| `breath_cycles` | integer | lap overall breath cycles |
| `position` | integer | position in heat at the end of the lap |


* * *


+ Parameters
    + id: 9976 (number, required) - Lap ID


+ Request ok (application/json)

    #### Examples

    ##### `curl` (Bash):

    ```bash
    $> curl -i -X PUT -H "Content-Type: application/json" \
            -H 'Authorization: "Bearer VALID-SESSION-JWT"' \
            -d '{"position": 3, "minutes": 0, "seconds": 39, "hundredths": 65 }' \
            "<API_HOST:PORT>/api/v3/lap/9976"
    ```

    ##### `RestClient` (Ruby):

    ```ruby
    > res = RestClient::Request.execute(
                method: :put,
                url: '<API_HOST:PORT>/api/v3/lap/9976',
                payload: {
                    position: 3,
                    minutes: 0,
                    seconds: 30,
                    hundredths: 65
                },
                headers: { "Authorization" => "Bearer VALID-SESSION-JWT"}
            )
    => <RestClient::Response 200 "true">
    ```

    * * *

    + Header

            Authorization: "Bearer VALID-SESSION-JWT"

    + Body

            {
                "position": 3,
                "minutes": 0,
                "seconds": 30,
                "hundredths": 65
            }

+ Response 200 (application/json)

        true


+ Request not found (application/json)

    The row for the specified ID must be existing in order to be edited.

    + Header

            Authorization: "Bearer VALID-SESSION-JWT"

    + Body

            {
                "position": 3,
                "minutes": 0,
                "seconds": 30,
                "hundredths": 65
            }

+ Response 200 (application/json)

        null


+ Request bad JWT (application/json)

    All JWTs expire: see [Session API docs](#sessions-session-post) for info.

    + Header

            Authorization: "Bearer BAD-OR-EXPIRED-JWT"

    + Body

            {
                "position": 3,
                "minutes": 0,
                "seconds": 30,
                "hundredths": 65
            }

+ Response 401 (application/json)

    + Header

            X-Error-Detail: "Invalid JWT token"

    + Body

            { "msg": "Unauthorized" }


+ Request no JWT (application/json)

            {
                "position": 3,
                "minutes": 0,
                "seconds": 30,
                "hundredths": 65
            }

+ Response 401 (application/json)

    + Header

            X-Error-Detail: "Missing JWT token"

    + Body

            { "msg": "Unauthorized" }


+ Request no grant (application/json)

            {
                "position": 3,
                "minutes": 0,
                "seconds": 30,
                "hundredths": 65
            }

+ Response 401 (application/json)

    + Header

            X-Error-Detail: "Invalid User grants"

    + Body

            { "msg": "Unauthorized" }



### create [POST]

Creates a new Lap, given the specified body parameters.

Association with MIR is optional to allow lap creation even before
the heat is over.

Returns a result text 'msg' on success, plus the 'new' row as JSON.

:key: => satisfy both conditions:
1. `Authorization` request header => valid JWT **required**
2. authenticated user must have CRUD grant on 'Lap' or have generic admin grants


#### Body Attributes:

|  Field name  | Data type |  description |
| --- | --- | --- |
| `meeting_program_id` | integer | **required**, associated MeetingProgram ID |
| `team_id` | integer | **required**, associated Team ID |
| `swimmer_id` | integer | **required**, associated Swimmer ID |
| `meeting_individual_result_id` | integer | associated MeetingIndividualResult ID |
| `reaction_time` | float | reaction time (when available; must be positive to be considered) |
| `minutes` | integer | lap time, minutes |
| `seconds` | integer | lap time, seconds |
| `hundredths` | integer | lap time, hundredths of seconds |
| `length_in_meters` | integer | lap length in meters |
| `minutes_from_start` | integer | overall minutes from heat start |
| `seconds_from_start` | integer | overall seconds from heat start |
| `hundredths_from_start` | integer | overall hundredths of second from heat start |
| `stroke_cycles` | integer | lap overall stroke cycles |
| `underwater_seconds` | integer | time spent underwater on turn/start, seconds |
| `underwater_hundredths` | integer | time spent underwater on turn/start, hundredths of a second |
| `underwater_kicks` | integer | underwater kicks after lap turn/start |
| `breath_cycles` | integer | lap overall breath cycles |
| `position` | integer | position in heat at the end of the lap |


* * *


+ Attributes
    + meeting_program_id: 161956 (number, required) - associated MeetingProgram ID
    + team_id: 1 (number, required) - associated Team ID
    + swimmer_id: 23 (number, required) - associated Swimmer ID
    + meeting_individual_result_id: 834879 (number, optional) - associated MeetingIndividualResult ID
    + reaction_time (number, optional)
    + minutes: 1 (number, optional)
    + seconds: 15 (number, optional)
    + hundredths: 97 (number, optional)
    + length_in_meters: 150 (number, optional)
    + minutes_from_start (number, optional)
    + seconds_from_start (number, optional)
    + hundredths_from_start (number, optional)
    + stroke_cycles (number, optional)
    + underwater_seconds (number, optional)
    + underwater_hundredths (number, optional)
    + underwater_kicks (number, optional)
    + breath_cycles (number, optional)
    + position (number, optional)


+ Request ok (application/json)

    #### Examples

    ##### `curl` (Bash):

    ```bash
    $> curl -i -X POST -H "Content-Type: application/json" \
            -d '{"meeting_individual_result_id": 834879, "meeting_program_id": 168301, \
                 "team_id": 1, "swimmer_id": 23, "length_in_meters": 150, \
                 "position": 5, "minutes": 1, "seconds": 15, "hundredths": 97}'
            "<API_HOST:PORT>/api/v3/lap"
    ```

    ##### `RestClient` (Ruby):

    ```ruby
    > res = RestClient.post('<API_HOST:PORT>/api/v3/lap',
            {
                "meeting_individual_result_id": 834879,
                "meeting_program_id": 168301,
                "team_id": 1,
                "swimmer_id": 23,
                "length_in_meters": 150,
                "position": 5,
                "minutes": 1,
                "seconds": 15,
                "hundredths": 97
            } )
    => <RestClient::Response 201 "{\"msg\":\"OK\",\"new\":{\"id\":...">

    > puts res.body
    {"msg":"OK","new":<NEW_ROW_AS_JSON>}
    ```

    * * *

    + Header

            Authorization: "Bearer VALID-SESSION-JWT"

    + Body

            {
                "meeting_individual_result_id": 834879,
                "meeting_program_id": 168301,
                "team_id": 1,
                "swimmer_id": 23,
                "length_in_meters": 150,
                "position": 5,
                "minutes": 1,
                "seconds": 15,
                "hundredths": 97
            }

+ Response 200 (application/json)

        {
            "msg": "OK",
            "new": "NEW_ROW_AS_JSON"
        }


+ Request bad JWT (application/json)

    All JWTs expire: see [Session API docs](#sessions-session-post) for info.

    + Header

            Authorization: "Bearer BAD-OR-EXPIRED-JWT"

    + Body

            {
                "meeting_individual_result_id": 834879,
                "meeting_program_id": 168301,
                "team_id": 1,
                "swimmer_id": 23,
                "length_in_meters": 150,
                "position": 5,
                "minutes": 1,
                "seconds": 15,
                "hundredths": 97
            }

+ Response 401 (application/json)

    + Header

            X-Error-Detail: "Invalid JWT token"

    + Body

            { "msg": "Unauthorized" }


+ Request no JWT (application/json)

    + Body

            {
                "meeting_individual_result_id": 834879,
                "meeting_program_id": 168301,
                "team_id": 1,
                "swimmer_id": 23,
                "length_in_meters": 150,
                "position": 5,
                "minutes": 1,
                "seconds": 15,
                "hundredths": 97
            }

+ Response 401 (application/json)

    + Header

            X-Error-Detail: "Missing JWT token"

    + Body

            { "msg": "Unauthorized" }


+ Request no grant (application/json)

    + Header

            Authorization: "Bearer VALID-SESSION-JWT"

    + Body

            {
                "meeting_individual_result_id": 834879,
                "meeting_program_id": 168301,
                "team_id": 1,
                "swimmer_id": 23,
                "length_in_meters": 150,
                "position": 5,
                "minutes": 1,
                "seconds": 15,
                "hundredths": 97
            }

+ Response 401 (application/json)

    + Header

            X-Error-Detail: "Invalid User grants"

    + Body

            { "msg": "Unauthorized" }



## delete [DELETE]

Allows the deletion of individual rows, given their `id`.

Returns `true` on success, an empty body when not found.

:key: => satisfy both conditions:
1. `Authorization` request header => valid JWT **required**
2. authenticated user must have CRUD grant on 'Lap' or have generic admin grants


#### Body Attributes:

+ Parameters
    + id: 9983 (number, required) - Lap ID of the row that has to be deleted


+ Request ok (application/json)

    #### Examples

    ##### `curl` (Bash):

    ```bash
    $> curl -i -X DELETE -H "Content-Type: application/json" \
            -H 'Authorization: "Bearer VALID-SESSION-JWT"' \
            "<API_HOST:PORT>/api/v3/lap/9983"
    ```

    ##### `RestClient` (Ruby):

    ```ruby
    > res = RestClient::Request.execute(
                method: :delete,
                url: '<API_HOST:PORT>/api/v3/lap/9983',
                headers: { "Authorization" => "Bearer VALID-SESSION-JWT"}
            )
    => <RestClient::Response 200 "true">
    ```

    * * *

    + Header

            Authorization: "Bearer VALID-SESSION-JWT"

+ Response 200 (application/json)

        true


+ Request not found (application/json)

    The row for the specified ID must be existing in order to be edited.

    + Header

            Authorization: "Bearer VALID-SESSION-JWT"

+ Response 200 (application/json)

        null


+ Request bad JWT (application/json)

    All JWTs expire: see [Session API docs](#sessions-session-post) for info.

    + Header

            Authorization: "Bearer BAD-OR-EXPIRED-JWT"

+ Response 401 (application/json)

    + Header

            X-Error-Detail: "Invalid JWT token"

    + Body

            { "msg": "Unauthorized" }


+ Request no JWT (application/json)

+ Response 401 (application/json)

    + Header

            X-Error-Detail: "Missing JWT token"

    + Body

            { "msg": "Unauthorized" }


+ Request no grant (application/json)

+ Response 401 (application/json)

    + Header

            X-Error-Detail: "Invalid User grants"

    + Body

            { "msg": "Unauthorized" }



# Lap list [/api/v3/laps{?page,per_page,meeting_individual_result_id,meeting_program_id,team_id,swimmer_id}]

+ Model (application/json)

    + Header

            Link: "<API_HOST:PORT/api/v3/laps?page=2&team_id=1>; rel=\"last\", <http://localhost:3000/api/v3/laps?page=2&team_id=1>; rel=\"next\""
            Total: 9275
            Per-Page: 25
            Page: 1

    + Body

            [
                // Lap details 1
                {
                    "id": 1,
                    // [...]
                },

                // Lap details 2
                {
                    "id": 2,
                    // [...]
                },

                // [...]
            ]


## list [GET]

The list of Laps associated to the specified filtering values,
returned as JSON and optionally filtered by any or all from:

- `meeting_individual_result_id`
- `meeting_program_id`
- `team_id`
- `swimmer_id`

Returns exact matches for all the parameters.

Optional pagination parameters for the request:

- `page`: current/selected page cursor
- `per_page`: total items per data page (default: 25)

:key: `Authorization` request header => valid JWT **required**

### Pagination

Pagination links will be returned in the `Link` _response header_, for all arrays with
more than 25 results.

Typical `Link` header format (single String, separated by COMMA+BLANK):

    "<REQ_URL_FOR_NEXT_PAGE>; rel=\"next\", <REQ_URL_FOR_LAST_PAGE>; rel=\"last\""


* * *


+ Parameters
    + meeting_program_id: 161956 (number, required) - associated MeetingProgram ID
    + team_id: 1 (number, required) - associated Team ID
    + swimmer_id: 23 (number, required) - associated Swimmer ID
    + meeting_individual_result_id: 834879 (number, optional) - associated MeetingIndividualResult ID
    + page: 1 (number, optional) - pagination: selected page
        + Default: 1
    + per_page: 25 (number, optional) - pagination: desired total rows per page
        + Default: 25


+ Request ok (application/json)

    ### Examples

    #### `curl` (Bash):

    ```bash
    $> curl -i -X GET -H "Content-Type: application/json" \
            -H 'Authorization: "Bearer VALID-SESSION-JWT"' \
            "<API_HOST:PORT>/api/v3/laps?team_id=1"
    ```

    #### `RestClient` (Ruby):

    _(Note that due to how the current version of RestClient handles the actual query parameters of the request,
    the `params` hash needs to be specified inside the `headers` hash.)_

    ```ruby
    > res = RestClient::Request.execute(
                method: :get,
                url: '<API_HOST:PORT>/api/v3/laps',
                headers: {
                    "Authorization" => "Bearer VALID-SESSION-JWT",
                    params: { team_id: 1 }
                }
            )
    => <RestClient::Response 200 "[{\"id\":1,...">
    ```

    * * *

    + Header

            Authorization: "Bearer VALID-SESSION-JWT"

+ Response 200

    [Lap list][]


+ Request not found (application/json)

    + Header

            Authorization: "Bearer VALID-SESSION-JWT"

+ Response 200 (application/json)

        []


+ Request bad JWT (application/json)

    All JWTs expire: see [Session API docs](#sessions-session-post) for info.

    + Header

            Authorization: "Bearer BAD-OR-EXPIRED-JWT"

+ Response 401 (application/json)

    + Header

            X-Error-Detail: "Invalid JWT token"

    + Body

            { "msg": "Unauthorized" }


+ Request no JWT (application/json)

+ Response 401 (application/json)
