# Group Users

## User [/api/v3/user/{id}]

### retrieve details [GET]
The User instance matching the specified `id` returned as JSON.

A valid JWT value is required for the `Authorization` request header.


* * *


#### Bash:

```
$> curl -i -X GET -H "Content-Type: application/json" \
        -H 'Authorization: "Bearer VALID-SESSION-JWT"' \
        "<API_HOST:PORT>/api/v3/user/1"
```


#### Ruby/`RestClient`:

```
> res = RestClient::Request.execute(method: :get, url: 'localhost:3000/api/v3/user/1',
           headers: { "Authorization" => "Bearer VALID-SESSION-JWT"} )
 => <RestClient::Response 200 "{\"id\":1, ...">
```


* * *



+ Parameters
    + id (number) - User ID

+ Request ok (application/json)

    + Header

            Authorization: "Bearer VALID-SESSION-JWT"

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "steve",
            "description": "Stefano Alloro",
            "swimmer_id": 142,
            "created_at": "2013-10-23T17:10:00.000Z",
            "updated_at": "2020-02-09T18:17:29.000Z",
            // [...]
            "email": "steve.alloro@not.an.actual.domain.com",
            // [...]
            "last_name": "Alloro",
            "first_name": "Stefano",
            "year_of_birth": 1969,
            // [...]
        }

+ Request ID not found (application/json)

    + Header

            Authorization: "Bearer VALID-SESSION-JWT"

+ Response 200 (application/json)

        null


+ Request bad JWT (application/json)

    + Header

            Authorization: "Bearer BAD-OR-EXPIRED-JWT"

+ Response 401 (application/json)

    + Header

            X-Error-Detail: "Invalid JWT token"

    + Body

            { "msg": "Unauthorized" }

+ Request JWT missing (application/json)

+ Response 401 (application/json)

    + Header

            X-Error-Detail: "Missing JWT token"

    + Body

            { "msg": "Unauthorized" }
