version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1

common-config: &common-config
  parallelism: 2
  working_directory: ~/goggles_api
  shell: /bin/bash --login
  environment:
    CI_OUTPUT: /tmp/ci-output
  docker:
    - image: cimg/ruby:3.1.4-node
      environment:
        RAILS_ENV: test
        BUNDLE_JOBS: 2
        BUNDLE_RETRY: 2
        BUNDLE_PATH: vendor/bundle
        PAGER: cat
        GIT_LFS_SKIP_SMUDGE: 1
    - image: cimg/mariadb:10.6.12
      environment:
        DATABASE_NAME: goggles_test
        DATABASE_USER: root
        PAGER: cat

common-folder-struct: &common-folder-struct
  name: Common folders & structure
  command: |
    mkdir -p $CI_OUTPUT/rubocop $CI_OUTPUT/brakeman $CI_OUTPUT/rspec tmp coverage
    mv config/database_ci.yml config/database.yml

common-bundle: &common-bundle
  name: Common Bundle
  command: |
    echo "Current Bundler with version:" && which bundler && bundle --version
    bundle config set path "vendor/bundle"
    GIT_LFS_SKIP_SMUDGE=1 bundle install

common-db-setup: &common-db-setup
  name: DB setup
  command: |
    sudo apt update
    sudo apt-get install mysql-client
    curl -L -o db/dump/test.sql.bz2 "https://github.com/steveoro/goggles_db/raw/master/spec/dummy/db/dump/test.sql.bz2"
    dockerize -wait tcp://localhost:3306 -timeout 1m
    RAILS_ENV=test bin/rails db:rebuild from=test to=test
    RAILS_ENV=test bin/rails db:migrate

jobs:
  rubocop:
    <<: *common-config
    steps:
      - checkout
      - run:
          <<: *common-folder-struct
      - ruby/install-deps:
          app-dir: ~/goggles_api
          key: goggles_api-v0600
      - ruby/rubocop-check:
          app-dir: ~/goggles_api
          format: pacman
          out-path: $CI_OUTPUT/rubocop/rubocop.xml

  brakeman:
    <<: *common-config
    steps:
      - checkout
      - run:
          <<: *common-folder-struct
      - ruby/install-deps:
          app-dir: ~/goggles_api
          key: goggles_api-v0600
      - run:
          name: Brakeman
          command: |
            bundle exec brakeman -A --except CheckForceSSL
      - store_test_results:
          path: $CI_OUTPUT/brakeman

  zeitwerk:
    <<: *common-config
    steps:
      - checkout
      - run:
          <<: *common-folder-struct
      - ruby/install-deps:
          app-dir: ~/goggles_api
          key: goggles_api-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: Zeitwerk check
          command: |
            bundle exec rake zeitwerk:check
      - store_test_results:
          path: $CI_OUTPUT

  rspec-A-F:
    <<: *common-config
    steps:
      - checkout
      - run:
          <<: *common-folder-struct
      - ruby/install-deps:
          app-dir: ~/goggles_api
          key: goggles_api-v0600
      - run:
          <<: *common-db-setup
      - ruby/rspec-test:
          app-dir: ~/goggles_api
          no_output_timeout: 5m
          out-path: $CI_OUTPUT/rspec
          include: spec/**/a*_spec.rb,spec/**/b*_spec.rb,spec/**/c*_spec.rb,spec/**/f*_spec.rb
          tag: type:model

  rspec-I-L:
    <<: *common-config
    steps:
      - checkout
      - run:
          <<: *common-folder-struct
      - ruby/install-deps:
          app-dir: ~/goggles_api
          key: goggles_api-v0600
      - run:
          <<: *common-db-setup
      - ruby/rspec-test:
          app-dir: ~/goggles_api
          no_output_timeout: 5m
          out-path: $CI_OUTPUT/rspec
          include: spec/**/i*_spec.rb,spec/**/l*_spec.rb
          tag: type:model

  rspec-M:
    <<: *common-config
    steps:
      - checkout
      - run:
          <<: *common-folder-struct
      - ruby/install-deps:
          app-dir: ~/goggles_api
          key: goggles_api-v0600
      - run:
          <<: *common-db-setup
      - ruby/rspec-test:
          app-dir: ~/goggles_api
          no_output_timeout: 5m
          out-path: $CI_OUTPUT/rspec
          include: spec/**/m*_spec.rb
          tag: type:model

  rspec-S:
    <<: *common-config
    steps:
      - checkout
      - run:
          <<: *common-folder-struct
      - ruby/install-deps:
          app-dir: ~/goggles_api
          key: goggles_api-v0600
      - run:
          <<: *common-db-setup
      - ruby/rspec-test:
          app-dir: ~/goggles_api
          no_output_timeout: 5m
          out-path: $CI_OUTPUT/rspec
          include: spec/**/s*_spec.rb
          tag: type:model

  rspec-T:
    <<: *common-config
    steps:
      - checkout
      - run:
          <<: *common-folder-struct
      - ruby/install-deps:
          app-dir: ~/goggles_api
          key: goggles_api-v0600
      - run:
          <<: *common-db-setup
      - ruby/rspec-test:
          app-dir: ~/goggles_api
          no_output_timeout: 5m
          out-path: $CI_OUTPUT/rspec
          include: spec/**/t*_spec.rb
          tag: type:model

  rspec-U:
    <<: *common-config
    steps:
      - checkout
      - run:
          <<: *common-folder-struct
      - ruby/install-deps:
          app-dir: ~/goggles_api
          key: goggles_api-v0600
      - run:
          <<: *common-db-setup
      - ruby/rspec-test:
          app-dir: ~/goggles_api
          no_output_timeout: 5m
          out-path: $CI_OUTPUT/rspec
          include: spec/**/u*_spec.rb
          tag: type:model

  deploy:
    # This is an example deploy job, not actually used by the workflow
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  build:
    jobs:
      - brakeman
      - rubocop
      - zeitwerk
      - rspec-A-F:
          requires:
            - brakeman
            - rubocop
      - rspec-I-L:
          requires:
            - brakeman
            - rubocop

      - rspec-M:
          requires:
            - rspec-A-F
      - rspec-S:
          requires:
            - rspec-I-L

      - rspec-T:
          requires:
            - rspec-M
      - rspec-U:
          requires:
            - rspec-S

    # - deploy:
    #     requires:
    #       - rspec
