name: DockerHub Versioned Release
run-name: DockeHub release by ${{ github.actor }}
on:
  release:
    types: [published]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI trigger job
        id: <customize id>
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        with:
          run_workflow_versioned: true
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
